# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gofmt
    - golines

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    rules:
      # Exclusion for errcheck: Error return value of `resp.Body.Close` is not checked (errcheck)
      # Reference: https://github.com/kisielk/errcheck/issues/101
      - linters: ["errcheck"]
        source: "^\\s*defer\\s+"