package provider

import (
	"context"

	"aembit.io/aembit"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &SignInPolicyResource{}
	_ resource.ResourceWithConfigure   = &SignInPolicyResource{}
	_ resource.ResourceWithImportState = &SignInPolicyResource{}
)

// NewSignInPolicyResource is a helper function to simplify the provider implementation.
func NewSignInPolicyResource() resource.Resource {
	return &SignInPolicyResource{}
}

// SignInPolicyResource is the resource implementation.
type SignInPolicyResource struct {
	client *aembit.CloudClient
}

// Metadata returns the resource type name.
func (r *SignInPolicyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_signin_policy"
}

// Configure adds the provider configured client to the resource.
func (r *SignInPolicyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = resourceConfigure(req, resp)
}

// Schema defines the schema for the resource.
func (r *SignInPolicyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			// ID field is required for Terraform Framework acceptance testing.
			"id": schema.StringAttribute{
				Description: "This identifier is generated by Terraform provider",
				Optional:    true,
				Computed:    true,
				// this is a static identifier to identify the SignInPolicy resource in the state,
				Default: stringdefault.StaticString("signinpolicy_identifier"),
			},
			"sso_required": schema.BoolAttribute{
				Description: "Activating it disables email/password sign-in except for users with SuperAdmin role",
				Required:    true,
			},
			"mfa_required": schema.BoolAttribute{
				Description: "Activating it enforces MFA for all users tenant-wide",
				Required:    true,
			},
		},
	}
}

// Read refreshes the Terraform state with the latest data.
func (r *SignInPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Get current state
	var state SignInPolicyResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get refreshed signInPolicy value from Aembit
	signInPolicy, err, _ := r.client.GetSignInPolicy(nil)
	if err != nil {
		resp.Diagnostics.AddWarning(
			"Error reading Aembit SignInPolicy",
			err.Error(),
		)

		return
	}

	state = convertSignInPolicyDTOToModel(ctx, signInPolicy)

	// Set refreshed state
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

func (r *SignInPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Get refreshed signInPolicy value from Aembit
	signInPolicy, err, _ := r.client.GetSignInPolicy(nil)
	if err != nil {
		resp.Diagnostics.AddWarning(
			"Error reading Aembit SignInPolicy",
			err.Error(),
		)
		return
	}

	state := convertSignInPolicyDTOToModel(ctx, signInPolicy)

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *SignInPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Get current state
	var state SignInPolicyResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Retrieve values from plan
	var plan SignInPolicyResourceModel
	diags = req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	var signInPolicy aembit.GetSignInPolicyDTO = convertSignInPolicyModelToDTO(ctx, plan)
	updateSignInResponse, err := UpdateSignInSettings(r.client, &signInPolicy)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating SignInPolicy",
			"Could not update SignInPolicy, unexpected error: "+err.Error(),
		)
		return
	}

	// update the state
	state.SSORequired = types.BoolValue(updateSignInResponse.SSORequired)
	state.MFARequired = types.BoolValue(updateSignInResponse.MFARequired)

	// Set state to fully populated data
	diags = resp.State.Set(ctx, state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

func (r *SignInPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	resp.Diagnostics.AddWarning("Not a real Create", "This is not a real Create, this step will only update the SignIn Policy settings.")

	// Retrieve values from plan
	var plan SignInPolicyResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	var signInPolicy aembit.GetSignInPolicyDTO = convertSignInPolicyModelToDTO(ctx, plan)
	updateSignInResponse, err := UpdateSignInSettings(r.client, &signInPolicy)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating SignInPolicy",
			"Could not update SignInPolicy, unexpected error: "+err.Error(),
		)
		return
	}

	// update the state
	plan.SSORequired = types.BoolValue(updateSignInResponse.SSORequired)
	plan.MFARequired = types.BoolValue(updateSignInResponse.MFARequired)

	// Set state to fully populated data
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	// set and return the state
}

func (r *SignInPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("Not a real Delete", "This is not a real Delete, this step will only reset the SignIn Policy settings to false.")

	// Retrieve values from state
	var state SignInPolicyResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := UpdateSignInSettings(r.client, &aembit.GetSignInPolicyDTO{SSORequired: false, MFARequired: false})
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating SignInPolicy",
			"Could not update SignInPolicy, unexpected error: "+err.Error(),
		)
		return
	}

	// update the state
	state.SSORequired = types.BoolValue(false)
	state.MFARequired = types.BoolValue(false)

	// Set state to fully populated data
	diags = resp.State.Set(ctx, state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

func UpdateSignInSettings(client *aembit.CloudClient, dto *aembit.GetSignInPolicyDTO) (*aembit.GetSignInPolicyDTO, error) {
	mfaRequestDTO := aembit.MFASignInPolicyDTO{MFARequired: dto.MFARequired}
	mfaResponseDTO, err := client.UpdateSignInPolicyMFA(mfaRequestDTO, nil)
	if err != nil {
		return nil, err
	}

	ssoRequestDTO := aembit.SSOSignInPolicyDTO{SSORequired: dto.SSORequired}
	ssoResponseDTO, err := client.UpdateSignInPolicySSO(ssoRequestDTO, nil)
	if err != nil {
		return nil, err
	}

	return &aembit.GetSignInPolicyDTO{SSORequired: ssoResponseDTO.SSORequired, MFARequired: mfaResponseDTO.MFARequired}, nil
}

// Model to DTO conversion methods.
func convertSignInPolicyModelToDTO(_ context.Context, model SignInPolicyResourceModel) aembit.GetSignInPolicyDTO {
	var dto aembit.GetSignInPolicyDTO
	dto.MFARequired = model.MFARequired.ValueBool()
	dto.SSORequired = model.SSORequired.ValueBool()
	return dto
}

// DTO to Model conversion methods.
func convertSignInPolicyDTOToModel(_ context.Context, dto aembit.GetSignInPolicyDTO) SignInPolicyResourceModel {
	var model SignInPolicyResourceModel
	model.MFARequired = types.BoolValue(dto.MFARequired)
	model.SSORequired = types.BoolValue(dto.SSORequired)
	// this is a static identifier to identify the SignInPolicy resource in the state,
	model.ID = types.StringValue("signinpolicy_identifier")
	return model
}
